<?php

/**
 * @file
 * Contains custom_stains.module.
 */

use Drupal\node\Entity\Node;


function custom_stains_theme()
{
  return [
    'custom_stains' => [
      'render element' => 'children',
    ],
    'footer_block' => array(
      'variables' => array('items' => null,),
    ),
    'header_block' => array(
      'variables' => array('items' => null,),
    ),
    'slider_block' => array(
      'variables' => array('items' => null,),
    ),
    'products_block' => array(
      'variables' => array('items' => null,),
    ),
    'featured_block' => array(
      'variables' => array('items' => null,),
    ),
    'coffee_page' => array(
      'variables' => array('items' => null,),
    ),
    'tools_page' => array(
      'variables' => array('items' => null,),
    ),
    'cups_page' => array(
      'variables' => array('items' => null,),
    ),
  ];
}
