<?php

/**
 * @file
 * Contains custom_stains.module.
 */

use Drupal\node\Entity\Node;
use \Drupal\Core\Form\FormStateInterface;


function custom_stains_theme()
{
  return [
    'custom_stains' => [
      'render element' => 'children',
    ],
    'footer_block' => array(
      'variables' => array('items' => null,),
    ),
    'header_block' => array(
      'variables' => array('items' => null,),
    ),
    'slider_block' => array(
      'variables' => array('items' => null,),
    ),
    'products_block' => array(
      'variables' => array('items' => null,),
    ),
    'featured_block' => array(
      'variables' => array('items' => null,),
    ),
    'coffee_page' => array(
      'variables' => array('items' => null,),
    ),
    'tools_page' => array(
      'variables' => array('items' => null,),
    ),
    'cups_page' => array(
      'variables' => array('items' => null,),
    ),
  ];
}

/**
 * Implements hook_form_alter().
 */
function custom_stains_form_alter(&$form, FormStateInterface $form_state, $form_id)
{
  if (strpos($form_id, 'commerce_order_item_add_to_cart_form_commerce_product') === 0) {
    $form['purchased_entity']['widget']['#title'] = t('Quantity');
    $form['purchased_entity']['#attributes']['class'][] = 'custom-select';
    $form['quantity']['#attributes']['class'][] = 'cart-plus-minus-box';
    $form['actions']['submit']['#value'] = '';
    $form['actions']['submit']['#attributes']['class'][] = 'zmdi zmdi-shopping-cart-plus';
  }
}
